# Generated by Django 5.2.17 on 2026-09-25 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_categoria_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaFinanceira',
            fields=[
                ('id_meta', models.AutoField(primary_key=True, serialize=False)),
                ('nome_meta', models.CharField(max_length=255)),
                ('valor_objetivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prazo', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta Financeira',
                'verbose_name_plural': 'Metas Financeiras',
                'ordering': ['prazo'],
            },
        ),
        migrations.CreateModel(
            name='PlanejamentoMensal',
            fields=[
                ('id_planejamento', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('limite_gastos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planejamentos_mensais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planejamento Mensal',
                'verbose_name_plural': 'Planejamentos Mensais',
                'ordering': ['-ano', '-mes'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'mes', 'ano'), name='planejamento_unico_por_usuario_mes_ano')],
            },
        ),
    ]
